# MinIO Prometheus Service Discovery Configuration
# This file contains all configuration options for the service

# MinIO Connection Settings
# Use the nginx load balancer service name within Docker network
minio_endpoint: "minio-1-1:9000"
minio_access_key: "admin"
minio_secret_key: "password123"
minio_use_ssl: false

# Service Settings
listen_addr: ":8080"
scrape_interval: "15s"
metrics_path: "/minio/metrics/v3"

# Bucket Filtering
bucket_pattern: "*"
bucket_exclude_pattern: ""
