version: '3.8'

services:
  # MinIO Node 1
  minio1:
    image: minio/minio:latest
    container_name: minio1
    hostname: minio1
    ports:
      - "9001:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "http://minio1:9000/mnt/drive-1/minio http://minio2:9000/mnt/drive-1/minio http://minio3:9000/mnt/drive-1/minio http://minio4:9000/mnt/drive-1/minio"
    command: server --console-address ":9001" --address ":9000"
    volumes:
      - minio1_drive1:/mnt/drive-1
    networks:
      - minio_cluster
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Node 2
  minio2:
    image: minio/minio:latest
    container_name: minio2
    hostname: minio2
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "http://minio1:9000/mnt/drive-1/minio http://minio2:9000/mnt/drive-1/minio http://minio3:9000/mnt/drive-1/minio http://minio4:9000/mnt/drive-1/minio"
    command: server --console-address ":9001" --address ":9000"
    volumes:
      - minio2_drive1:/mnt/drive-1
    networks:
      - minio_cluster
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Node 3
  minio3:
    image: minio/minio:latest
    container_name: minio3
    hostname: minio3
    ports:
      - "9005:9000"
      - "9006:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "http://minio1:9000/mnt/drive-1/minio http://minio2:9000/mnt/drive-1/minio http://minio3:9000/mnt/drive-1/minio http://minio4:9000/mnt/drive-1/minio"
    command: server --console-address ":9001" --address ":9000"
    volumes:
      - minio3_drive1:/mnt/drive-1
    networks:
      - minio_cluster
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Node 4
  minio4:
    image: minio/minio:latest
    container_name: minio4
    hostname: minio4
    ports:
      - "9007:9000"
      - "9008:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "http://minio1:9000/mnt/drive-1/minio http://minio2:9000/mnt/drive-1/minio http://minio3:9000/mnt/drive-1/minio http://minio4:9000/mnt/drive-1/minio"
    command: server --console-address ":9001" --address ":9000"
    volumes:
      - minio4_drive1:/mnt/drive-1
    networks:
      - minio_cluster
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Load Balancer for MinIO API (optional, for external access)
  nginx:
    image: nginx:alpine
    container_name: minio-nginx
    ports:
      - "9000:80"   # MinIO API
      - "9090:81"   # MinIO Console (changed from 9001 to avoid conflict)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio_cluster

  minio-prometheus-sd:
    build: .
    container_name: minio-prometheus-sd
    ports:
      - "8080:8080"
    # Option 1: Using configuration file (Recommended)
    volumes:
      - ./config.yaml:/app/config.yaml
    command: >
      ./minio-prometheus-sd
      -config-file=/app/config.yaml
    networks:
      - minio_cluster
    depends_on:
      minio1:
        condition: service_healthy
      minio2:
        condition: service_healthy
      minio3:
        condition: service_healthy
      minio4:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      minio-prometheus-sd:
        condition: service_healthy
    networks:
      - minio_cluster

networks:
  minio_cluster:
    driver: bridge

volumes:
  # MinIO Node drives (one per node)
  minio1_drive1:
  minio2_drive1:
  minio3_drive1:
  minio4_drive1:
  prometheus_data:
