global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # MinIO Server Metrics
  - job_name: 'minio-server'
    http_sd_configs:
      - url: 'http://localhost:8080/sd?job=minio-server'
        refresh_interval: 15s
    scheme: http
    bearer_token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ5MDg2MzQ1ODR9.olf5w9-ET1uV-obK9vDGE8Inc0XYJ85c2iP9C_pRxJcysXHRsnb4zGbF9OOrWZfNLRpRyXNRCWfdgOh9J4HizQ'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__metrics_path__]
        target_label: __metrics_path__
      - source_labels: [__scheme__]
        target_label: __scheme__

  # MinIO Bucket Metrics - All buckets in a single job
  - job_name: 'minio-buckets'
    http_sd_configs:
      - url: 'http://localhost:8080/sd?job=minio-buckets'
        refresh_interval: 15s
    scheme: http
    bearer_token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ5MDg2MzQ1ODR9.olf5w9-ET1uV-obK9vDGE8Inc0XYJ85c2iP9C_pRxJcysXHRsnb4zGbF9OOrWZfNLRpRyXNRCWfdgOh9J4HizQ'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__metrics_path__]
        target_label: __metrics_path__
      - source_labels: [__scheme__]
        target_label: __scheme__
      - source_labels: [bucket]
        target_label: bucket
      - source_labels: [bucket_creation]
        target_label: bucket_creation

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
