name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  BINARY_NAME: eos_mb_http_sd
  GO_VERSION: '1.24.6'

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: darwin
            arch: amd64
            suffix: darwin-amd64
          - os: darwin
            arch: arm64
            suffix: darwin-arm64
          - os: windows
            arch: amd64
            suffix: windows-amd64.exe
          - os: windows
            arch: arm64
            suffix: windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o ${{ env.BINARY_NAME }}-${{ matrix.suffix }} main.go
          echo "Binary built: ${{ env.BINARY_NAME }}-${{ matrix.suffix }}"

      - name: Create checksums
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            sha256sum ${{ env.BINARY_NAME }}-${{ matrix.suffix }} > ${{ env.BINARY_NAME }}-${{ matrix.suffix }}.sha256
          else
            shasum -a 256 ${{ env.BINARY_NAME }}-${{ matrix.suffix }} > ${{ env.BINARY_NAME }}-${{ matrix.suffix }}.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suffix }}
          path: |
            ${{ env.BINARY_NAME }}-${{ matrix.suffix }}
            ${{ env.BINARY_NAME }}-${{ matrix.suffix }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.version
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        run: |
          # Create a new release
          gh release create ${{ steps.get_version.outputs.version }} \
            --title "Release ${{ steps.get_version.outputs.version }}" \
            --notes "Release ${{ steps.get_version.outputs.version }} of ${{ env.BINARY_NAME }}" \
            --draft=false \
            --prerelease=false

      - name: Upload Release Assets
        run: |
          # Upload all binaries to the release
          for suffix in linux-amd64 linux-arm64 darwin-amd64 darwin-arm64 windows-amd64 windows-arm64; do
            if [ -d "artifacts/$suffix" ]; then
              echo "Uploading $suffix assets..."
              gh release upload ${{ steps.get_version.outputs.version }} \
                artifacts/$suffix/${{ env.BINARY_NAME }}-$suffix \
                artifacts/$suffix/${{ env.BINARY_NAME }}-$suffix.sha256
            fi
          done

      - name: Create and Upload Checksums
        run: |
          # Create a combined checksums file
          echo "## Checksums" > checksums.txt
          echo "" >> checksums.txt
          for file in artifacts/*/*.sha256; do
            if [ -f "$file" ]; then
              cat "$file" >> checksums.txt
            fi
          done
          
          # Upload checksums file
          gh release upload ${{ steps.get_version.outputs.version }} checksums.txt
